#### File Description ####
' - Dieses Script dient grundsätz der Darstellung von ClassIntervalls, welches zur Darstellung bestimmter Clusterkriterien dient. Das Vorgehen bezieht sich auf das Script von Roger Bivand der Oslo Summmer School.
  - Die betrachteten Dateien hier sind KreismSMiExAvgMask (ein SPDF generiert mit raster::extract für ein layer) und KreisSMI_spdf (über alle layer)
  - Verschieden break Algorithmen werden hier betrachtet, wie etwa Quantile, Fixierte, und Standard Deviation ... 
   ... Fisher Jenkins (The Jenks optimization method, also called the Jenks natural breaks classification method, is a data clustering method designed to determine the best arrangement 
    of values into different classes.) 
  - Zum einen werden die geordnenten Werte der Daten geplottet mit den entsprechenden Breaks
  - Zum anderen werden dann farblich markierte Maps erstellt mit diesen Breaks
'


#### Output
## Files
' 
'
## Plots
' Die Plots wurden jeweils für KreismSMiExAvgMask und KreisSMI_spdf erstellt
  - Plots showing the data values and the breaks
  - Spatial Plots showing the spatial distribtuion of the breaks
'


#### Input and Dependencies
' - KreismSMiExAvgMask <- ExtractSMI.R
  - KreisSMI_spdf <- MergeSMI_Yield.R
'

#### Packages ####
library(sp)
library(rgdal)
library(raster)
library(lattice)
library(rasterVis)
library(maptools)
library(RColorBrewer)
library(classInt)
library(ncdf)
library(zoo)
library(foreign)
library(rgeos)
library(parallel)
library(snow)


########################################################################################################
################################# ClassIntervalls mit KreismSMiExAvgMask ###############################
########################################################################################################


#### Load SMI extracted to Kreislevel generated with extract function ####
KreismSMiExAvgMask<-readOGR("./data/data_raw", "KreismSMiExAvgMask")


KreismSMiExAvgMaskValues<-KreismSMiExAvgMask[!is.na(KreismSMiExAvgMask$x),]
summary(KreismSMiExAvgMaskValues)

#### Projection der ClassIntervalls ####
## hier muss ich mir noch überlegen, ob das irgendwie Sinn macht

display.brewer.all() 
pal <- brewer.pal(9, "Blues")

## Fixed Breaks
at=seq(0, 1,0.1)
fixed <- classIntervals(KreismSMiExAvgMaskValues$x, n=9, style="fixed", fixedBreaks=at)

##Quantile Breaks
q5 <- classIntervals(KreismSMiExAvgMaskValues$x, n=9, style="quantile")

## Fisher Breaks
fj5 <- classIntervals(KreismSMiExAvgMaskValues$x, n=9, style="fisher")

## Veränderte Fisher Breaks
fisher <- classIntervals(KreismSMiExAvgMaskValues$x, n=length(Sd$brks)-1, style="fisher")

## Standard Deviation
Sd <- classIntervals(KreismSMiExAvgMaskValues$x, n = 9, style = "sd")

## Plot all in one window ##
oopar <- par(mfrow=c(5,1), mar=c(2,1,3,1))
plot(fixed, pal=pal, main="Fixed", xlab="", ylab="")
plot(q5, pal=pal, main="Quantile", xlab="", ylab="")
plot(fj5, pal=pal, main="Fisher-Jenks natural breaks", xlab="", ylab="")
plot(fisher, pal=pal, main="Fisher-Jenks natural breaks/2", xlab="", ylab="")
plot(Sd, pal=pal, main="SD", xlab="", ylab="" )
par(oopar)


###########################
#### Spplot fixed brks ####
# Funktion findcolours funktioniert bei spplot nicht, daher muss man die breaks manuel wählen
atfixed=fixed$brks
atfixed[1] <- atfixed[1] - atfixed[1]/100
atfixed[length(atfixed)] <- atfixed[length(atfixed)] + atfixed[length(atfixed)]/100
mSMiExAvgMaskPltfixed <- spplot(KreismSMiExAvgMaskValues, zcol="x",at=atfixed,col.regions= colorRampPalette(pal)(length(atfixed)-1) , main="SMI Germany, Kreise, aus 100*100m masked raster, Quantiles")

findColours(q5, pal) # Eventuell geht diese Funktion bei ssplot nicht

#### Spplot: quantile brks ####
atq5=q5$brks
atq5[1] <- atq5[1] - atq5[1]/100
atq5[length(atq5)] <- atq5[length(atq5)] + atq5[length(atq5)]/100
mSMiExAvgMaskPltQuantile <- spplot(KreismSMiExAvgMaskValues, zcol="x", at=atq5,col.regions= colorRampPalette(pal)(length(atfixed)-1), main="SMI Germany, Kreise, aus 100*100m masked raster, Quantiles")


#### Spplot: Fisher brks ####
at1=fisher$brks
at1[1] <- at1[1] - at1[1]/100
at1[length(at1)] <- at1[length(at1)] + at1[length(at1)]/100
mSMiExAvgMaskPltNauralBreak <- spplot(KreismSMiExAvgMaskValues, zcol="x",at=at1, col.regions= colorRampPalette(pal)(length(at1)-1) , main="SMI Germany, Kreise, aus 100*100m masked raster, Fisher-Jenks natural breaks")

###################################################################################################
################################# ClassIntervalls mit KreisSMI_spdf ###############################
###################################################################################################


#### Load SMI extracted to Kreislevel generated by Stephan Thober and binded in 4km_SMI script ####
KreisSMI_spdf<-readShapePoly("./data/data_raw/KreisSMI_spdf.shp")

### Consider year 2003 ####
KreisSMI_spdfValues<-KreisSMI_spdf[!is.na(KreisSMI_spdf$SMMai2003),]
summary(KreisSMI_spdfValues)

#### Projection der ClassIntervalls ####
## hier muss ich mir noch überlegen, ob das irgendwie Sinn macht

display.brewer.all() 
pal <- brewer.pal(9, "Blues")

## Fixed
at=seq(0, 1,0.1)
fixed <- classIntervals(KreisSMI_spdfValues$SMMai2003, n=9, style="fixed", fixedBreaks=at)

## Quantile
q5 <- classIntervals(KreisSMI_spdfValues$SMMai2003, n=9, style="quantile")

## Fisher
fj5 <- classIntervals(KreisSMI_spdfValues$SMMai2003, n=9, style="fisher")

fisher <- classIntervals(KreisSMI_spdfValues$SMMai2003, n=length(Sd$brks)-1, style="fisher")

## Standard Deviation
Sd <- classIntervals(KreisSMI_spdfValues$SMMai2003, n = 9, style = "sd")


## Plot all in one window ##
oopar <- par(mfrow=c(5,1), mar=c(2,1,3,1))
plot(fixed, pal=pal, main="Fixed", xlab="", ylab="")
plot(q5, pal=pal, main="Quantile", xlab="", ylab="")
plot(fj5, pal=pal, main="Fisher-Jenks natural breaks", xlab="", ylab="")
plot(fisher, pal=pal, main="Fisher-Jenks natural breaks/2", xlab="", ylab="")
plot(Sd, pal=pal, main="SD", xlab="", ylab="" )
par(oopar)

#### Spplot fixed brks ####
# Funktion findcolours funktioniert bei spplot nicht, daher muss man die breaks manuel wählen
atfixed=fixed$brks
atfixed[1] <- atfixed[1] - atfixed[1]/100
atfixed[length(atfixed)] <- atfixed[length(atfixed)] + atfixed[length(atfixed)]/100

## Plot
mSMiExAvgMaskPltfixed <- spplot(KreisSMI_spdfValues, zcol="SMMai2003",at=atfixed,col.regions= colorRampPalette(pal)(length(atfixed)-1) , main="SMI Germany, Kreise, aus 100*100m masked raster, Quantiles")

findColours(q5, pal) # Eventuell geht diese Funktion bei ssplot nicht

#### Spplot: quantile brks ####
atq5=q5$brks
atq5[1] <- atq5[1] - atq5[1]/100
atq5[length(atq5)] <- atq5[length(atq5)] + atq5[length(atq5)]/100

## Plot
mSMiExAvgMaskPltQuantile <- spplot(KreisSMI_spdfValues, zcol="SMMai2003", at=atq5,col.regions= colorRampPalette(pal)(length(atfixed)-1), main="SMI Germany, Kreise, aus 100*100m masked raster, Quantiles")


#### Spplot: fisher - jenkins brks ####
at1=fisher$brks
at1[1] <- at1[1] - at1[1]/100
at1[length(at1)] <- at1[length(at1)] + at1[length(at1)]/100
mSMiExAvgMaskPltNauralBreak <- spplot(KreisSMI_spdfValues, zcol="SMMai2003",at=at1, col.regions= colorRampPalette(pal)(length(at1)-1) , main="SMI Germany, Kreise, aus 100*100m masked raster, Fisher-Jenks natural breaks")




##########################################
#### sp::over #### 

# Diese Funktion könnte der Funktion aus der UFZ -Library sehr ähnlich sein, welche von Stefan zu extraction der ComIDs aus den Polygon in die Raster
# Auflösung verwendet wurde
# Ist vor allem raster::extract sehr ähnlich, und scheibar auch schneller


###########################################
#### Zugreifen auf einen Slot aus einem Spatial.Dataframe
olinda1$area <- sapply(slot(olinda1, "polygons"), slot, "area") 

###########################################
#### RgoogleMaps
# Möglich, google maps als Hintergrund zu benutzen

##########################################
##### osmar
# Möglich, open street map einzubinden. Ist besser kompatibel


#########################################
#### graphics::identify(coordinates(KreismSMI)) # damit kann ich via cursor mir die ComID ausgeben lassen
# 